<?php

class Good extends Model
{
    public $id;
    public $name;
    public $price;
    public $info;

    /**
     * @return mixed
     */
    protected function getTableName():string
    {
        return 'goods';
    }

    public function getAll()
    {
        return parent::getAll(); // TODO: Change the autogenerated stub
    }
}
